spring.application.name=puebacrud
# configuracion de la base de datos MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/litigando?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=JUAN1021666804

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
